// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OEg0weAl7OuK377DhrBTfmTjUhfSme0',
    appId: '1:949162944890:web:1fbc6be045b14d23154ec3',
    messagingSenderId: '949162944890',
    projectId: 'swift-buy-437a2',
    authDomain: 'swift-buy-437a2.firebaseapp.com',
    storageBucket: 'swift-buy-437a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsK4B9UWIFugXjvUy-ABVhsJA4j5iW6js',
    appId: '1:949162944890:android:f632e40985f97063154ec3',
    messagingSenderId: '949162944890',
    projectId: 'swift-buy-437a2',
    storageBucket: 'swift-buy-437a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7z26EXKaTub1OikGwIUd_xT4dq5O7r4',
    appId: '1:949162944890:ios:b0684dbdea30118c154ec3',
    messagingSenderId: '949162944890',
    projectId: 'swift-buy-437a2',
    storageBucket: 'swift-buy-437a2.appspot.com',
    iosBundleId: 'com.example.swiftBuy',
  );
}
